[package]
name = "sm"
version = "0.1.0"
authors = ["Jess Bees <jesse@toomanybees.com>"]

[dependencies]
snes-bitplanes = { path = "../snes-bitplanes" }
lib-samus = { path = "../lib-samus" }
byteorder = "1.2"
